// Generated by tools/engine-model.mjs from a recording of the car pulling through its gears: do not edit by hand.

/**
 * One timbre of the engine, measured over the recording's frames at about
 * `firing` Hz (the firing frequency, rpm / 15 for a V8):
 *   orders       amplitude of each harmonic of the cycle frequency (rpm / 120), 1..40, relative to the firing order (8)
 *   noise        the noise between the orders by third octave (ENGINE_BANDS), dB from its loudest band
 *   noiseToTone  the noise's RMS over the orders' RMS
 *   pulse        how deeply the noise above 1.5 kHz pulses at the firing rate (0..1)
 */
export interface EngineTimbre {
  firing: number
  orders: number[]
  noise: number[]
  noiseToTone: number
  pulse: number
}

export const ENGINE_BANDS = [31.5, 39.7, 50, 63, 79.4, 100, 126, 158.8, 200, 252, 317.5, 400, 504, 635, 800.1, 1008, 1270, 1600.1, 2016, 2540, 3200.2, 4032, 5080, 6400.4, 8064, 10160, 12800.8, 16128]

/** low revs (about 2205 rpm, 51 frames) and high (about 4968 rpm, 117 frames) */
export const ENGINE_TIMBRE: Record<'low' | 'high', EngineTimbre> = {
  low: {
    firing: 147,
    orders: [0.019, 0.033, 0.034, 0.04, 0.057, 0.169, 0.247, 1, 0.202, 0.257, 0.191, 0.199, 0.158, 0.173, 0.163, 0.359, 0.123, 0.132, 0.099, 0.151, 0.129, 0.115, 0.104, 0.152, 0.079, 0.082, 0.052, 0.064, 0.059, 0.069, 0.058, 0.101, 0.068, 0.078, 0.064, 0.07, 0.062, 0.073, 0.097, 0.13],
    noise: [-32.5, -50, -29, -35, -27.2, -24.2, 0, -1.7, -7.1, -11.8, -7.9, -6.6, -11.1, -9.5, -3, -9.5, -11.7, -14.5, -16.1, -16.3, -20.6, -21.9, -23.2, -21.5, -36.6, -45.6, -49, -50],
    noiseToTone: 0.459,
    pulse: 0.17,
  },
  high: {
    firing: 331.2,
    orders: [0.029, 0.028, 0.038, 0.041, 0.059, 0.177, 0.164, 1, 0.166, 0.145, 0.135, 0.157, 0.11, 0.236, 0.138, 0.589, 0.134, 0.144, 0.143, 0.119, 0.107, 0.129, 0.088, 0.157, 0.062, 0.052, 0.063, 0.071, 0.053, 0.078, 0.059, 0.084, 0.058, 0.043, 0.043, 0.034, 0.035, 0.043, 0.035, 0.049],
    noise: [-50, -39.8, -29.6, -19.4, -25.8, -32.2, -13.9, -22.5, -7.1, -11.2, -2.9, -2.8, -4.2, -4.9, 0, -4.7, -2.4, -13, -12.6, -15.1, -15.8, -17.9, -17.1, -15.7, -32, -39.7, -43.1, -47.6],
    noiseToTone: 0.723,
    pulse: 0.2,
  },
}
